remote_theme: pages-themes/minimal@v0.2.0
title: "Snapback" 
permalink: /:title/
baseurl: ""
description: "Snapback by momentismedical"
url: "https://snapback.momentismedical.dev"

# This ensures the build isn't skipping your posts
collections:
  posts:
    output: true

# To show the buttons (Current state)
show_downloads: true

plugins:
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-feed 
  - jekyll-seo-tag

markdown: kramdown 
kramdown: 
input: GFM
