theme: jekyll-theme-minimal
title: snap_back 
permalink: /:title/
baseurl: "/snapback"
description: Bookmark this to keep an eye on my project updates!
url: "https://snapback.momentismedical.dev"

# This ensures the build isn't skipping your posts
collections:
  posts:
    output: true

# To show the buttons (Current state)
show_downloads: true

# To hide the buttons (If you want a cleaner look)
show_downloads: false

plugins:
  - jekyll-gist
  - jekyll-remote-theme
